[package]
name        = "spite-sampling"
description = "Logit processors and token samplers"
version.workspace    = true
edition.workspace    = true
rust-version.workspace = true
license.workspace    = true
repository.workspace = true

[dependencies]
spite-abi  = { workspace = true }
thiserror  = { workspace = true }
